config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :donations
  resources :confirmations, only: [:new, :create, :index, :show]
  resources :users, only: [:show]
  resources :chatrooms, only: [:show] do
    resources :messages, only: [:create]
  end
  resources :reviews, only: [:new, :create, :show]
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :donations
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  belongs_to :user
  belongs_to :donation
end

app/models/confirmation.rb
class Confirmation < ApplicationRecord
  belongs_to :donation
  belongs_to :user
end

app/models/donation.rb
class Donation < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  belongs_to :category

  has_many :confirmations
  has_many :chatrooms, dependent: :destroy

  validates :description, presence: true, length: { in: 10..550 }
  validates :image, :location, :quantity, :donation_name, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_donation_name_and_description,
                  against: [:donation_name, :description],
                  using: {
                    tsearch: { prefix: true } # <-- now half of the word will return something!
                  }

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user

  def sender?(a_user)
    user.id == a_user.id
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  validates :content, length: { maximum: 280 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :donations
  has_many :confirmations
  has_many :chatrooms, through: :donation

  has_one_attached :avatar

  validates :avatar, file_size: { less_than_or_equal_to: 1.megabytes },
            file_content_type: { allow: ['image/jpeg', 'image/svg', 'image/png', 'image/gif'] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, [:avatar]])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, [:avatar]])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @donation = Donation.find(params[:donation_id])
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
    authorize @chatroom
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
  before_action :confirmation_params, only: %i[create]
  before_action :donation_id, only: %i[new create]
  before_action :user_id, only: %i[new create]
  def index
    @confirmations =  policy_scope(Confirmation)
  end

  def show
   @confirmation = Confirmation.where(user_id:current_user)
   authorize @confirmation
  end

  def new
    @confirmation = Confirmation.new
    authorize @confirmation
  end

  def create
    @confirmation = Confirmation.new(confirmation_params)
    # This link the user to the donation created
    @confirmation.user = current_user
    authorize @confirmation
  end

  private

  def confirmation_params
    params.require(:confirmation).permit(:donation_id, :user_id)
  end

  def donation_id_
    @donation = Donation.find(params[:id])
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :donation_params, only: %i[create update]
  before_action :donation_id, only: %i[show edit update destroy]

  def index
    if params[:query].present?
      @donations = policy_scope(Donation).search_by_donation_name_and_description(params[:query]).order(created_at: :desc)
      @markers = @donations.geocoded.map do |donation|
        {
          lat: donation.latitude,
          lng: donation.longitude,
          info_window: render_to_string(partial: "info_window", locals: { donation: donation })
        }
      end
    else
      @donations = policy_scope(Donation).order(created_at: :desc)
      @markers = @donations.geocoded.map do |donation|
        {
          lat: donation.latitude,
          lng: donation.longitude,
          info_window: render_to_string(partial: "info_window", locals: { donation: donation })
        }
      end
    end
  end

  def show
    @chatroom = Chatroom.where(donation: @donation).first
    @chatroom = Chatroom.create!(user: current_user, donation: @donation, name: @donation.donation_name) if @chatroom.nil?
    @message = Message.new
    authorize @donation
  end

  def new
    @donation = Donation.new
    authorize @donation
  end

  def create
    @donation = Donation.new(donation_params)
    # This link the user to the donation created
    @donation.user = current_user
    authorize @donation

    if @donation.save
      redirect_to donations_path
    else
      render :new
    end
  end

  def edit
    authorize @donation
  end

  def update
    @donation.update(donation_params)
    authorize @donation
    @confirmation = Confirmation.create!(user: current_user, donation: @donation)
    redirect_to donations_path
  end

  def destroy
    @donation.destroy
    authorize @donation
    redirect_to donations_path
  end

  private

  def donation_params
    params.require(:donation).permit(:donation_name, :description, :image, :category_id, :location, :quantity, :available, :donation_received)
  end

  def donation_id
    @donation = Donation.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    authorize @message
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        message: render_to_string(partial: "message", locals: { message: @message }),
        sender_id: @message.user.id
      )
      head :ok
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def donation_params
    params.require(:donation).permit(:title, :body, :photo)
  end

  def home
    @donations = Donation.all
  end

  def log_out
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
    authorize @review
  end

  def show
    @review = Review.find(params[:id])
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.user = current_user
    authorize @review

    if @review.save
      redirect_to review_path(@review)
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def avatar_params
    params.require(:user).permit(:title, :body, :avatar)
  end

  def show
    @user = User.find(params[:id])
    @total_donations = Confirmation.where(user_id:current_user).count
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/donations/_form.html.erb
<div class="container mt-4 px-5">
  <h1 class="create__new__donation">Tell us what you need:</h1>
</div>
<div class="container text_form_donations px-5">
  <%= simple_form_for @donation do |f| %>
    <%= f.input :donation_name, label: 'Add what you need here', error: 'Donation name is mandatory, please specify one' %>
    <%= f.input :quantity, label: 'Add the quantity here.' %>
    <%= f.input :description, label: 'What is the necessity of your needs/donation? Add the description here' %>
    <%= f.association :category, collection: Category.order(:name), prompt: 'Choose a Category' %>
    <%= f.input :location, prompt: 'Add your city, state and country here' %>
    <%= f.input :image, as: :file %>
    <%= f.button :submit, class: "btn btn-info mt-2 mb-4" %>
    <div><%= link_to 'Back', root_path, class: "btn btn-sucess mb-3" %></div>
  <% end %>
</div>

app/views/donations/_info_window.html.erb
<h2><%= donation.donation_name %></h2>
<p><%= donation.location %></p>

app/views/donations/edit.html.erb
<%= render 'form', donation: @donation %>

app/views/donations/index.html.erb
<div class="container d-flex">
  <div class="container campaigns">
    <div class="title-campaigns">Discover who needs your support</div>
    <div class="heading-campaigns">People all over the world are using what the HELP! and finding great supporters around here.
    Need some help today?</div>
    <br>
    <%=link_to "/donations/new", class:"start-here" do %> <p class="btn btn-edit"><i class="fas fa-heart"></i> START HERE</p>
    <%end%>
  </div>
</div>

<div class="container_donations d-flex h-100 w-100 position-relative">
  <div class="grid-donations mx-2 mt-2 h-100 d-flex flex-wrap justify-content-around" style="width: 60%;">
    <% if @donations.empty? %>
      <h5>Sorry, we couldn't find what you're looking for.</h5>
    <% else %>
      <% @donations.each_with_index do |donation, index| %>
        <div class="donation-card card d-flex flex-column align-items-center p-2 m-2">
          <div class="donation-img thumbnail ">
            <img src="<%= cl_image_path donation.image.key %>" class="portrait" alt="Image">
          </div>
          <div class="card-body d-flex flex-column bg-white donation-body justify-content-between">
          <div class="d-flex justify-content-between">
            <h4 class="card-title"><strong><%= donation.donation_name %></strong></h4>
            <div>
              <i class="fas fa-eye"></i> <%= rand(50..499) %> views <!-- Comentario aqui ><!-->
            </div>
          </div>
          <div class="mb-2 mt-2 d-flex align-content-center">
            <label for=""><i class="fas fa-map-marker-alt"></i> <%= donation.location %></label>
          </div>
            <p class="card-text"><%= donation.description.truncate(100) %></p> <!-- Comentario aqui ><!-->
          <div class="mb-2 mt-2 d-flex align-content-center">
            <label for=""><i class="fas fa-hands-helping"></i> <%= donation.donation_received %> persons donated</label>
          </div>
            <%= link_to 'Donation', donation,class:"btn-chat" %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="flex-grow-1 h-100 mapbox mx-4 mt-3 position-sticky" style="top:10vh; z-index:0">
    <div style="width: 100%; height: 90vh;"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
  <br>
</div>
<br>

app/views/donations/new.html.erb
<%= render 'form', donation: @donation %>

app/views/donations/show.html.erb
<br>
<div class="container">
<div class="row justify-content-between">
  <div class= "col-xs-6 col-md-6">
    <div class="card-donation-page card justify-content-between align-items-center">
      <div class="thumbnail-donation ">
        <img src="<%= cl_image_path @donation.image.key %>" class="portrait-donation" alt="Image">
      </div>
      <div class="card-body justify-content-between">
        <h3 class="card-title"><strong><%= @donation.donation_name%></strong></h3>
        <h6 class="card-infos text-muted px-4"><%= @donation.description %></h6>
        <p class="card-text text-center"><strong>Category: </strong><%= @donation.category.name %></p>
        <p class="card-text text-center"><strong>Quantity: </strong><%= @donation.quantity %></p>
        <p class="card-text text-center"><strong>Donations received: </strong><%= @donation.donation_received %></p>
        <p class="card-text text-center"><strong>Address: </strong><%= @donation.location %></p>
        <div>
          <% if @donation.user_id == current_user.id %>
            <div class="btn-block">
              <%= link_to 'Delete', donation_path(@donation), class: "button btn-chat-delete", method: :delete, data: { confirm: 'Are you sure?' } %>
              <%= link_to 'Edit', edit_donation_path(@donation), class: "button btn-chat" %>
              <%= link_to 'Back', donations_path, class: "button btn-chat" %>
            </div>
          <% else %>
            <div class=" btn-block justify-content-around">
              <%= link_to 'Donate now', donation_path(@donation, donation:{ donation_received: @donation.donation_received + 1, available: @donation.quantity == @donation.donation_received + 1 ? false : true }), method: :patch,  class: "btn-donation-now", data: {confirm: "Thank you for your donation!"} %>
              <%= link_to 'Back', donations_path, class: "btn-chat" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xs-6 col-md-6">
    <div class="chatroom"
      data-controller="chatroom-subscription"
      data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
      data-chatroom-subscription-current-user-id-value="<%= current_user.id %>">

      <h1>#<%= @chatroom.name %></h1>

      <div class="messages" data-chatroom-subscription-target="messages">
        <% @chatroom.messages.each do |message| %>
          <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
            <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
                <%= render "messages/message", message: message %>
            </div>
          </div>
        <% end %>
      </div>
      <%= simple_form_for [@chatroom, @message],
      remote: true,
      html: {data: {action: "ajax:success->chatroom-subscription#resetForm"}, class: "d-flex" } do |f| %>
        <%= f.input :content,
        label: false,
        placeholder: "Message ##{@chatroom.name}",
        wrapper_html: {class: "flex-grow-1"} %>
        <%= f.submit "Send", class: "btn-send mb-3" %>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>wtHELP</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.9.2/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.9.2/mapbox-gl.css' rel='stylesheet' />

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  <div class="d-flex flex-column w-100 h-100">
    <%= render 'shared/navbar' %>
    <%# <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div id="message-<%= message.id %>">
  <small>
    <strong><%= message.user.first_name %></strong>
    <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p class="message-chat"><%= message.content %></p>
</div>

app/views/pages/home.html.erb
<div class="row pe-4 m-2 banner-margin-top">
  <div class="col-lg-6 col-sm-12 d-flex justify-content-center align-items-center mx-auto text-white text-center">
    <div class="container call-to-action d-flex flex-column">
      <h1 class="display-4">what the <strong>HELP</strong>!</h1>
      <p class="lead mb-2">A place for KINDNESS,</p>
      <p class ="lead mb-0 mt-2">A place for YOU.</p>
      <br>
      <%=link_to "/donations/new", class:"start-here" do %>
        <p class="btn btn-edit"><i class="fas fa-heart"></i> START HERE</p>
      <%end%>
    </div>
  </div>
  <div class="col-lg-6 col-sm-8">
    <img class="image" src="https://images.unsplash.com/photo-1593113598332-cd288d649433?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80">
  </div>
</div>
<div class="container mt-5 mb-0">
  <h2 class="call-started d-flex justify-content-center"> Here's what you need to start :</h2>
  <div class="row justify-content-center align-content-center mt-5">
    <div class="steps123 d-flex flex-column align-items-center" style="width: 30%;">
      <div class="step-number-container d-flex justify-content-center align-items-center mb-4">
        <h3 class="step-number ">1</h3>
      </div>
      <div class="card col-lg-3 col-sm-12 ">
        <img src="https://cdn-icons-png.flaticon.com/512/7290/7290863.png" alt>
        <br>
        <h4 class="h4-steps-cards"> Let's start with the basics </h4>
        <p class="p_name_steps"> Sign up with your name and location</p>
      </div>
    </div>
    <div class="steps123 d-flex flex-column align-items-center ml-5 mr-5" style="width: 30%;">
      <div class="step-number-container d-flex justify-content-center align-items-center mb-4">
        <h3 class="step-number ">2</h3>
      </div>
      <div class="card col-lg-3 col-sm-12" style="height: 345.59px;">
        <img src="https://cdn-icons-png.flaticon.com/512/3911/3911932.png" alt>
        <br>
        <h4 class="h4-steps-cards"> Tell us your story </h4>
        <p class="p_name_steps"> Let our helpers know what you need </p>
      </div>
    </div>
    <div class="steps123 d-flex flex-column align-items-center" style="width: 30%;">
      <div class="step-number-container d-flex justify-content-center align-items-center mb-4">
        <h3 class="step-number ">3</h3>
      </div>
      <div class="card col-lg-3 col-sm-12">
        <img src="https://cdn-icons-png.flaticon.com/512/8021/8021362.png" alt>
        <br>
        <h4 class="h4-steps-cards"> Share with friends and family </h4>
        <p class="p_name_steps"> There are plenty of helpers around here </p>
      </div>
    </div>
  </div>
  <br>
</div>
<div class="container">
  <div class="row align-items-center">
    <div class="col-lg-3 col-sm-12 justify-content-center card-product mt-5 mb-5">
      <img src="https://cdn-icons-png.flaticon.com/512/7736/7736297.png" />
    </div>
    <div class="col-lg-9 col-sm-12 justify-content-center">
      <div class="container">
        <h2 class="butwhy">But why?</h2>
        <br>
        <p class="text-p-charity">what the HELP! was created for people with a <strong>big heart</strong> and great intentions.
        We connect people willing to assist others throughout difficult times of their lives and ensure they are guided on every step of the way.
        Afterall, we believe that we can't always help everyone, but everyone can always help someone. ☺️</p>
      </div>
    </div>
  </div>
</div>
<div class="row row-count">
  <h1 class="counting-title">These many people were supported by WTH</h1>
  <p class="counting-header mt-3 mb-4">Still reading? Here are some real numbers for you.</p>

  <div class="counter d-flex justify-content-center mt-4">
    <div class="col-md-2 col-md-offset-2">
      <h1><span class="value-counting">2,873</span></h1>
      <p class="subtitle-counting"> CAUSES HELPED IN 2021</p>
    </div>

    <div class="col-md-2">
      <h1><span class="value-counting">3,326+</span></h1>
      <p class="subtitle-counting">ACTIVE HELPERS</p>
    </div>

    <div class="col-md-2">
      <h1><span class="value-counting">4,945+</span></h1>
      <p class="subtitle-counting">PEOPLE USED WTH </p>
    </div>

    <div class="col-md-2">
      <h1><span class="value-counting">1,000+</span></h1>
      <p class="subtitle-counting">SATISFIED USERS</p>
    </div>
  </div>
</div>

<div class="container">
  <div class="row align-items-center">
    <div class="col-lg-9 col-sm-12 justify-content-center">
      <div class="container">
        <h2 class="text-align-start">Used what the HELP! and would like to leave a review?</h2>
        <br>
        <br>
        <br>
           <%=link_to "/reviews/new", class:"start-here" do %>
           <p class="btn btn-edit"><i class="fas fa-heart"></i> TELL US WHAT YOU THINK </p>
           <br>
          <%end%>
      </div>
    </div>
    <div class="col-lg-3 col-sm-12 justify-content-center card-product mt-4 mb-3">
      <img src="https://cdn-icons-png.flaticon.com/512/4359/4359854.png">
    </div>
  </div>
</div>

  <div class="row justify-content-center align-items-center my-5">
    <figure class="snip1390 col-lg-3 col-sm-12 m-5">
      <img src="https://res.cloudinary.com/dykf9cult/image/upload/v1662231135/development/j2tk5yo2kb57aceziy3xmerew59z.jpg" alt="profile-sample3" class="profile" />
      <figcaption>
        <h2>Ana Ferreira</h2>
        <h4>Sao Paulo, SP, Brazil</h4>
        <blockquote>&nbspGetting help was never so easy! This website helped me raise what I needed to pursue my dream and complete my master's degree. Thank you so much to all the helpers out there!</blockquote>
      </figcaption>
    </figure>
    <figure class="snip1390 col-lg-3 col-sm-12 m-5">
      <img src="https://res.cloudinary.com/dykf9cult/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1662677350/development/WhatsApp_Image_2022-09-06_at_8.31.02_PM_1_epctbh.jpg" alt="profile-sample5" class="profile" />
      <figcaption>
        <h2>Anthony Watts</h2>
        <h4>Dili, Timor, East Timor</h4>
        <blockquote>&nbspNeeded blood donation for my son after a car accident, never thought I'd get so many people supporting so quickly. I'd recommend it to anyone. Words are not enough, THANK YOU! </blockquote>
      </figcaption>
    </figure>
    <figure class="snip1390 col-lg-3 col-sm-12 m-5">
      <img src="https://res.cloudinary.com/dykf9cult/image/upload/v1662231131/development/8s5q71jiotmhvcr7g8kakivszzfo.jpg" alt="profile-sample6" class="profile" />
      <figcaption>
        <h2>Patti Malach</h2>
        <h4>Saskatoon, SK, Canada</h4>
        <blockquote>&nbspLove the community and how helpful people can be. This website brings the best out of people, and encourages someone who just needs to see who's around to help. </blockquote>
      </figcaption>
    </figure>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container p-5 mb-5">
  <div class="row">
    <div class="col-xs-4">
      <%= simple_form_for @review do |f| %>
        <%= f.input :content %>
        <%= f.input :rating, collection: (1..5).to_a.reverse!, label: "Rate your experience", include_blank: false %>
        <div>
          <%= f.submit "Send your review", class: "btn btn-info", style: "margin-top: 2rem;"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/show.html.erb
<div class="container">
  <h3 class= "text-center mt-4 mb-4">Thanks for your review !</h3>
  <div id="success" class= "mb-4">
    <div class="face mt-2">
      <div class="eye"></div>
      <div class="eye right"></div>
      <div class="mouth happy"></div>
    </div>
    <div class="shadow scale"></div>
    <div class="message"><p><%= @review.content %></p></div>
    <br>
    <div id= "stars" class= "d-flex align-content-center align-items-center m">
      <% @review.rating.times do %>
        <i class="fas fa-star"></i>
      <% end %>
    </div>
    <div>
      <%= link_to "Back to Home", root_path, class: "btn button-box btn-outline-secondary " %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="profile d-flex justify-content-center mt-2">
  <figure class="figure-profile p-5 d-flex justify-content-around
  align-items-center ">
    <% if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, :size => "400x400", class:"border border-3 rounded-circle"%>
          <% else %>
              <%= image_tag ("download.jpeg")%>
          <% end %>
    <!--<img class="photo-profile border border-3 rounded-circle m-5" src="//s3-us-west-2.amazonaws.com/s.cdpn.io/55758/random-user-31.jpg" alt="" />-->
  </figure>

  <div class="list list-profile bg-white border border-3 m-5 border rounded-5 px-5 py-3" >
      <h2>Name</h2>
      <p><%= current_user.first_name %> <%= current_user.last_name %></p>
      <h2>Email </h2>
      <p><%= current_user.email %></p>
      <h2>My Donations</h2>
        <dd><%= @total_donations %> donations realized</dd>
      <h2>Hometown</h2>
        <dd>Sao Paulo, Brazil</dd>
      <h2>Rewards</h2>
        <div>
        <img src= "https://cdn-icons-png.flaticon.com/32/7602/7602822.png"alt>
        </div>
      <div class="edit-account pt-2">
          <%= link_to "Edit my account", edit_user_registration_path(current_user), class:"btn-chat" %></p>
      </div>
      <div class="see-donations pt-1">
        <%= link_to "See my donations", confirmation_path(current_user), class:"btn-chat" %></p>
      </div>
  </div>
</div> <!-- end profile -->